FROM node
LABEL application="workshop create sample app BE-2"

ARG BUILD_DATE
LABEL org.label-schema.build-date=$BUILD_DATE

ENV CUSTOM_BUILD_VERSION="1.0.0"

WORKDIR /app/my-api

ADD ./src/app-b .

RUN npm install express

EXPOSE 3000

CMD node server.js