FROM  nginx
LABEL application="workshop create sample api routing"

ARG BUILD_DATE
LABEL org.label-schema.build-date=$BUILD_DATE

ENV CUSTOM_BUILD_VERSION="1.0.0"

ADD ./src/ingress/default.conf /etc/nginx/conf.d/default.conf
