apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
  labels:
  {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val }}
  {{- end }}
spec:
  containers:
    - name: {{ .Release.Name }}
      image: {{ .Values.image }}
      {{ if eq .Values.app.env "Enable" }}
      env:
        - name: CUS_ENV
          values: enable 
      {{ end }}

