name: My-Workshop

on:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      image-version: ${{ steps.set-image-version.outputs.image-version }}
    steps:
      - name: Set Image Version
        id: set-image-version
        run: |
          echo "IMAGE_VERSION=1.0.0"
          echo "::set-output name=image-version::1.0.0"

  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: check server-info
        run: lsb_release -a

      - name: git checkout
        run: git clone -b sample-app-0 https://github.com/nukoolmu/public-laboratory.git

      - name: docker login
        run: docker login -u nukoolm -p ${{ Secrets.DOCKER_REGISTRY }}

      - name: build and push
        run: |
          cd public-laboratory 

          docker build -f Dockerfile-appB . -t nukoolm/sample-app:${{ needs.prepare.outputs.image-version }}
          docker push nukoolm/sample-app:${{ needs.prepare.outputs.image-version }}
      
  approve:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Approval
        uses: paz-lavi/wait-for-approval@v1.0.0

  deploy:
    needs: [build, approve]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Image
        run: |
          echo "Deploying my-image:${{ needs.prepare.outputs.image-version }}"
          # Add your deployment steps here