name: my-workflow
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'input your software version'
        required: true
        default: '1.0.0'
        type: string
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
  build:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Use environment variable
        run: echo "The value of IMAGE_TAG is: ${{ env.IMAGE_TAG }}"