name: main-example-flow
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'input your software version'
        required: true
        default: '1.0.0'
        type: string
  push: 
    branches: [main-1]


env:
  IMAGE_NAME: "sample-app"
  IMAGE_TAG: ${{ github.event.inputs.version }}
jobs:

  prepare:
    runs-on: ubuntu-latest
    steps:

      - name: Set Tag on Workflow Dispatch
        if: github.event_name == 'workflow_dispatch'
        run: echo "CUSTOM_TAG=${{ github.event.inputs.version }}" >>$GITHUB_ENV
  build:      
    runs-on: ubuntu-latest
    needs: prepare
    if: ${{ always() }}
    env:
      CUSTOM_TAG: ${{ env.CUSTOM_TAG }}
    steps:
      - name: mockup deployed
        run: |
         echo "Deploying ${{ env.IMAGE_NAME }}:${IMAGE_TAG}"
         echo "github env ${{ env.IMAGE_TAG }}"
         echo "CUSTOM_TAG ${{ env.CUSTOM_TAG }} or $CUSTOM_TAG"