name: Lab-Workflow
on:
  push:
    branches:
      - main
env:
  WORDING: "Piyapan"

jobs:
  build: 
    runs-on: ubuntu-latest
    outputs:
      image-version: ${{ steps.create-variable.outputs.BUILD_ARGS }}
    steps:
      - name: check github environment
        run: hostname
      
      - name: create-variable
        run: |
          echo "BUILD_ARGS=prod-1.0.0" >> $GITHUB_ENV
          echo "BUILD_ARGS=prod-1.0.0" >> $GITHUB_OUTPUT

      - name: build application
        run: echo "build for ${{ env.WORDING }} by $BUILD_ARGS "

  deploy: 
    runs-on: self-hosted
    needs: build
    steps:
      - name: check github environment
        run: hostname
      - name: deploy app
        run: echo "deploying app version ${{ needs.build.outputs.BUILD_ARGS}}  ${BUILD_ARGS}"        
