name: sample-flows

# Controls when the workflow will run
on:
  push: 
    branches: [main]

jobs:
  pre-test:
    runs-on: ubuntu-latest
    steps:
      - name: Preparation
        run: echo "This is Preparation steps"

      - name: full test
        run: echo "test-complete"

  call-extjob:
    uses: corp-ais/cpc-ate/.github/workflows/00-simple.yaml@poc