name: example-flow
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check server-info
        run: lsb_release -a

      - name: git checkout
        run: git clone -b sample-app-0 https://github.com/nukoolmu/public-laboratory.git

      - name: change directory
        run: | 
          cd public-laboratory
          ls -lrt

      - name: docker login
        run: docker login -u nukoolm -p ${{ Secrets.DOCKER_REGISTRY }}

      - name: build and push
        run: | 
          docker build -f Dockerfile-appB . -t nukoolm/sample-app:github-1.0
          docker push nukoolm/sample-app:github-1.0