name: sample-flows

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'input your software version'
        required: true
        default: '1.0.0'
        type: string
  push:
    branches:
      - main


jobs:
  pre-test:
    runs-on: ubuntu-latest
    steps:
      - name: Preparation
        run: echo "This is Preparation steps"

      - name: full test
        run: echo "test-complete"

  ext-job:
    uses: corp-ais/cpc-ate/.github/workflows/00-simple.yaml@poc
    secrets: inherit